### ISSUE TITLE
Windows: How to set up the development environment

### ISSUE THREAD

**Issue by japaric** [japaric/copper#11]
This section is empty. :scream_cat:

**Comment by andylokandy** [comment]
I recommend [GNU ARM Embedded Toolchain](https://launchpad.net/gcc-arm-embedded/+download) using by zinc.rs. It provides `arm-none-eabi-gcc` `arm-none-eabi-nm` and more . Also, linux-like CLI is an important part, which allow you to use `nm` `file` `ld`, ect. For most version of Window, we can use [Babun](https://babun.github.io/) to setup easily. It contains out-of-the-box `Cygwin` `oh-my-zsh` `bash` and `git`, but if this book uses any tool that have not been transplanted to windows, it can not help. For the user using win10, here is a better choice. Microsoft released a beta win10 in June, 2016, with [Bash on Ubuntu on Windows](https://msdn.microsoft.com/en-us/commandline/wsl/about). It runs a virtual machine for linux and sets up the environment. Its advantage is that we can run `apt-get` on real linux., but the disadvantage is that user must swith their win10 into beta version. Installing a virtual box is a bad idea, while `Bash on Ubuntu on Windows` embedded the linux command into window's native CLI, the virtual box can't even touch win's filesystem.

**Comment by andylokandy** [comment]
This book may help [[RustyGecko - Developing Rust on Bare-Metal]](https://brage.bibsys.no/xmlui/bitstream/handle/11250/2352353/12925_FULLTEXT.pdf?sequence=1&isAllowed=y)

**Comment by japaric** [comment]
@goandylok 

Awesome tips. I think the instructions will include installing some sort of shell like MinGW (is that what's called?) or Babun like you mention. IMO, the main instructions shouldn't require Bash-On-Ubuntu/Windows 10 but they should mention that as an option. I also agree that the instructions shouldn't say install a VM with Linux.

> This book may help [RustyGecko - Developing Rust on Bare-Metal]

That's a great resource; lots of good stuff in it. Are you one of the authors or do you know if the authors will be okay with me adding a link to that document to the Copper book Resources section?

**Comment by andylokandy** [comment]
Thx XD
Neither do I. I just found it on Google.

**Comment by japaric** [comment]
> Neither do I. I just found it on Google.

Ha, OK. I just added RustyGecko to the resources. I'm sure they won't mind :wink:.
