### ISSUE TITLE
macOS - xargo build fails without cmake

### ISSUE THREAD

**Issue by jcsoo** [japaric/copper#33]
When attempting `cargo install xargo`, the build fails in the libssh2-sys crate because there is no cmake installed by default on OSX.

`brew install cmake` fixes the problem.

**Comment by japaric** [comment]
As time goes by, we find out that Xargo needs more and more dependencies, it seems. The copper book, at this point, is probably out of date in that regard but the Xargo [README](https://github.com/japaric/xargo#dependencies) should be up to date. We should point to that in the book.

**Comment by japaric** [comment]
Xargo 0.2.0+ no longer depends on system C libraries or cmake.

Closing.
