### ISSUE TITLE
Cargo configuration file

### ISSUE THREAD

**Issue by dzebleckis** [japaric/copper#49]
Hello,

I'm not completely sure if this is a real issue, however while following https://japaric.github.io/copper/first/build.html I got stuck for some time while trying to compile program. The problem was that I saved https://japaric.github.io/copper/first/config.toml with extension "*.toml", while cargo expects it to be without. After looking at the instructions I see that there are several places where it mentions `.cargo/config` and not `.cargo/config.toml`, however maybe it would be worth to change file not to have extension in repository or make a notice for absent-minded ones like me,  what do you think? I could make a PR if needed.
And thanks for the great material.

**Comment by japaric** [comment]
> I'm not completely sure if this is a real issue

You are the second person to bring this up 😄.

The issue is that if the file (in the src directory) has no extension then `mdbook` won't copy it to the book directory. We could, however, remove the extension and add a post-processing step to .travis.yml to copy the file "manually".
